# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency=false

# Caching disabled on purpose. It causes subtle breakages when running tasks inside and outside sandboxed environments.  
org.gradle.configuration-cache=false
org.gradle.caching=false

# Increase JVM heap for Gradle daemon
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
