#!/bin/bash

# If running into cache/stale issues, run:
#   ./gradlew --stop
# The re-run
IDEA_JVM_ARGS="-Dsun.java2d.uiScale.enabled=false" IDEA_PROJECT=~/code/github.com/benjamin-thomas/7guis/rescript-7guis exec ./gradlew runIde
